const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
const wizard=fs.readFileSync('assets/profile-wizard.js','utf8');
const profile=fs.readFileSync('assets/user-profile.js','utf8');
const css=['styles.css','cloud-sync.css','profile-wizard.css','home-organizer.css','phone-visual-qa.css','language.css','network-usage.css','theme.css','readable-glass.css'].map(file=>fs.readFileSync('assets/'+file,'utf8')).join('\n');

async function fixture(page,theme='light'){
  page.wizardErrors=[];page.on('pageerror',error=>page.wizardErrors.push(error.message));
  await page.route(/https?:\/\/(?!127\.0\.0\.1:4173)/,route=>route.abort());
  await page.route('**/assets/profile-avatar-previews/*.svg',route=>{const name=new URL(route.request().url()).pathname.split('/').pop();return route.fulfill({contentType:'image/svg+xml',body:fs.readFileSync('assets/profile-avatar-previews/'+name,'utf8')})});
  await page.route('**/wizard-fixture',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="he" dir="rtl" data-theme="${theme}" data-surface-theme="classic"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><body class="home-page"><section class="cloud-account-backdrop"><section class="cloud-account"><button data-profile-wizard-open>עריכת פרופיל</button></section></section></html>`}));
  await page.goto('/wizard-fixture');
  await page.evaluate(()=>{
    window.user={id:'A',email:'a@example.invalid',user_metadata:{display_name:'שם קיים',travelmate_preferences:{pace:'relaxed',interests:['nature'],learningEnabled:false}}};window.calls=[];window.profileEvents=[];window.activeUrls=new Set();
    const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);
    URL.createObjectURL=value=>{const url=create(value);activeUrls.add(url);return url};URL.revokeObjectURL=url=>{activeUrls.delete(url);revoke(url)};
    const bitmap=createImageBitmap;window.decoded=[];window.createImageBitmap=async(...args)=>{const result=await bitmap(...args);decoded.push({width:result.width,height:result.height,options:args[1]});return result};
    window.generationCalls=[];window.generationPeak=0;window.generationInFlight=0;window.generationFailures={};
    window.TravelMateCloud={generateAvatarForOwner:async(owner,style,photo,signal)=>{
      generationCalls.push({owner,style,size:photo.size});generationInFlight++;generationPeak=Math.max(generationPeak,generationInFlight);
      try{
        if(window.generationWait)await new Promise(resolve=>{(window.finishGeneration||(window.finishGeneration=[])).push(resolve)});
        if(signal.aborted)throw new DOMException('Cancelled','AbortError');
        if(window.generationFailures[style]){window.generationFailures[style]--;throw new Error('AVATAR_GENERATION_FAILED')}
        const source=await bitmap(photo),canvas=document.createElement('canvas');canvas.width=1024;canvas.height=1024;const c=canvas.getContext('2d');c.drawImage(source,0,0,1024,1024);source.close();c.fillStyle=['#f30','#07f','#0b5','#fa0','#b4f','#555'][['classic','tokyo-neon','japanese-calm','beach-journey','manga-action','cinematic'].indexOf(style)];c.fillRect(0,0,1024,24);
        return await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.85));
      }finally{generationInFlight--}
    },getSession:async()=>({user:window.user}),uploadAvatar:async(file,options)=>{calls.push({kind:'avatar',owner:options.ownerId,size:file.size,type:file.type,style:options.style});const result=await bitmap(file);calls[calls.length-1].dimensions=[result.width,result.height];result.close();if(window.avatarWait)await new Promise(resolve=>window.finishAvatar=resolve);return{data:{user:{id:options.ownerId,user_metadata:{}}},error:null}},updateProfileForOwner:async(owner,name,preferences)=>{calls.push({kind:'profile',owner,name,preferences});return{data:{user:{id:owner,user_metadata:{display_name:name,travelmate_preferences:preferences}}},error:null}}};
    addEventListener('travelmate:profile-change',event=>profileEvents.push(event.detail.user.id));
  });
  await page.addScriptTag({content:profile});await page.addScriptTag({content:wizard});
}
test.afterEach(async({page})=>{expect(page.wizardErrors||[]).toEqual([])});
async function picture(page,{orientation=1,large=false}={}){
  const base64=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=3200;canvas.height=1600;const c=canvas.getContext('2d');c.fillStyle='#e6a032';c.fillRect(0,0,1600,1600);c.fillStyle='#2472b8';c.fillRect(1600,0,1600,1600);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.85));const bytes=new Uint8Array(await blob.arrayBuffer());return btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(''))});
  let bytes=Buffer.from(base64,'base64');
  if(orientation!==1){const exif=Buffer.from([255,225,0,34,69,120,105,102,0,0,73,73,42,0,8,0,0,0,1,0,18,1,3,0,1,0,0,0,orientation,0,0,0,0,0,0,0]);bytes=Buffer.concat([bytes.subarray(0,2),exif,bytes.subarray(2)])}
  if(large){const padded=Buffer.alloc(20*1024*1024);bytes.copy(padded);bytes=padded}
  return{name:'portrait.jpg',mimeType:'image/jpeg',buffer:bytes};
}
async function open(page){await page.locator('[data-profile-wizard-open]').click();await expect(page.locator('[data-profile-gallery]')).toBeEnabled()}
async function styles(page,file){await page.locator('[data-profile-gallery]').setInputFiles(file);await expect(page.locator('[data-profile-next]')).toBeEnabled();await page.locator('[data-profile-next]').click();await expect(page.locator('[name="avatarStyle"]')).toHaveCount(6);await expect(page.locator('[name="avatarStyle"][value="classic"]')).toBeEnabled();await page.waitForFunction(()=>document.querySelectorAll('.profile-style-card img').length===6);await page.locator('[name="avatarStyle"][value="classic"]').check();await expect(page.locator('[data-profile-next]')).toBeEnabled()}
async function bounded(page){expect(await page.locator('.profile-wizard').evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBe(true);expect(await page.locator('.profile-wizard').evaluate(n=>getComputedStyle(n).direction)).toBe('rtl')}
for(const width of [390,430])for(const theme of ['light','dark'])test(`wizard real canvas, keyboard, preferences and offline at ${width} ${theme}`,async({page})=>{
  await page.setViewportSize({width,height:844});await fixture(page,theme);await open(page);await bounded(page);expect(await page.locator('.cloud-account-backdrop').evaluate(n=>n.inert)).toBe(true);expect(await page.locator('.profile-wizard-backdrop').evaluate(n=>Number(getComputedStyle(n).zIndex))).toBeGreaterThan(await page.locator('.cloud-account-backdrop').evaluate(n=>Number(getComputedStyle(n).zIndex)));
  const colors=await page.locator('.profile-wizard').evaluate(n=>({surface:getComputedStyle(n).backgroundColor,text:getComputedStyle(n).color}));if(theme==='dark')expect(colors.surface).not.toBe('rgb(255, 255, 255)');
  await styles(page,await picture(page,{orientation:6,large:width===390&&theme==='light'}));await bounded(page);if(theme==='dark')expect(await page.locator('.profile-wizard').evaluate(n=>getComputedStyle(n).backgroundImage)).not.toContain('206, 230, 250');
  expect(await page.evaluate(()=>decoded[0])).toMatchObject({width:1024,height:2048});
  const crop=await page.locator('[data-profile-crop]').evaluate(canvas=>{const c=canvas.getContext('2d');return{top:Array.from(c.getImageData(256,16,1,1).data),bottom:Array.from(c.getImageData(256,496,1,1).data)}});expect(crop.top[0]).toBeGreaterThan(crop.bottom[0]);expect(crop.bottom[2]).toBeGreaterThan(crop.top[2]);
  const images=await page.locator('.profile-style-card img').evaluateAll(async images=>Promise.all(images.map(async img=>{const bytes=await(await fetch(img.src)).arrayBuffer();return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).join(',')})));
  expect(new Set(images).size).toBe(6);
  await page.locator('[name="avatarStyle"][value="beach-journey"]').focus();await page.keyboard.press('Space');await expect(page.locator('[value="beach-journey"]')).toBeChecked();
  await page.locator('[data-profile-next]').click();await page.keyboard.press('Shift+Tab');await expect(page.locator('[data-profile-save]')).toBeFocused();await page.locator('.profile-extra-details summary').click();await expect(page.locator('[name="displayName"]')).toHaveValue('שם קיים');await expect(page.locator('[name="learningEnabled"]')).not.toBeChecked();
  for(const value of ['culture','food','history','shopping','nightlife'])await page.locator('[name="interests"][value="'+value+'"]').check();await page.locator('[name="interests"][value="photography"]').click();await expect(page.locator('[name="interests"]:checked')).toHaveCount(7);await expect(page.locator('[name="interests"][value="photography"]')).toBeChecked();
  await page.locator('[name="displayName"]').fill('שם חדש');await page.locator('[name="pace"]').selectOption('active');await page.locator('[data-profile-back]').click();await page.locator('[data-profile-next]').click();await expect(page.locator('[name="pace"]')).toHaveValue('active');await bounded(page);await page.screenshot({path:test.info().outputPath('review-'+width+'-'+theme+'.png')});
  await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,value:false});dispatchEvent(new Event('offline'))});await expect(page.locator('[data-profile-save]')).toBeDisabled();expect(await page.evaluate(()=>calls.length)).toBe(0);
  await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,value:true});dispatchEvent(new Event('online'))});await page.locator('[data-profile-save]').focus();await page.keyboard.press('Tab');await expect(page.locator('[data-profile-wizard-close]')).toBeFocused();
  await page.locator('[data-profile-save]').click();await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();
  expect(await page.evaluate(()=>calls)).toEqual([expect.objectContaining({kind:'avatar',owner:'A',style:'beach-journey',dimensions:[512,512],size:expect.any(Number)}),expect.objectContaining({kind:'profile',owner:'A',name:'שם חדש',preferences:expect.objectContaining({pace:'active',learningEnabled:false})})]);
  expect(await page.evaluate(()=>activeUrls.size)).toBe(0);await expect(page.locator('[data-profile-wizard-open]')).toBeFocused();
});
test('invalid images cannot advance without a valid existing photo',async({page})=>{
  await fixture(page);await open(page);const file=await picture(page);await page.locator('[data-profile-gallery]').setInputFiles({...file,name:'spoof.png'});await expect(page.locator('[data-profile-wizard-status]')).toHaveAttribute('role','alert');await expect(page.locator('[data-profile-next]')).toBeDisabled();
  await page.locator('[data-profile-gallery]').setInputFiles({name:'broken.jpg',mimeType:'image/jpeg',buffer:Buffer.from([255,216,255,0])});await expect(page.locator('[data-profile-wizard-status]')).toHaveAttribute('role','alert');await expect(page.locator('[data-profile-next]')).toBeDisabled();expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});
test('logout during asynchronous style generation releases URLs and cannot repaint a new session',async({page})=>{
  await fixture(page);await open(page);await page.locator('[data-profile-gallery]').setInputFiles(await picture(page));await expect(page.locator('[data-profile-next]')).toBeEnabled();
  await page.evaluate(()=>{const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb,...args){original.call(this,blob=>window.finishBlob=()=>cb(blob),...args)}});
  await page.locator('[data-profile-next]').click();await page.waitForFunction(()=>window.finishBlob);
  await page.evaluate(()=>dispatchEvent(new CustomEvent('travelmate:home-auth',{detail:{authenticated:false}})));await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();await page.evaluate(()=>finishBlob());
  await open(page);await expect(page.locator('[data-profile-styles] [name="avatarStyle"]')).toHaveCount(0);await expect(page.locator('[data-profile-next]')).toBeDisabled();expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});
test('account switch during upload never publishes a stale profile or updates successor preferences',async({page})=>{
  await fixture(page);await open(page);await styles(page,await picture(page));await page.locator('[data-profile-next]').click();await page.evaluate(()=>window.avatarWait=true);await page.locator('[data-profile-save]').click();await page.waitForFunction(()=>window.finishAvatar);
  await page.evaluate(()=>{window.user={id:'B',email:'b@example.invalid',user_metadata:{}};dispatchEvent(new CustomEvent('travelmate:home-auth',{detail:{authenticated:true}}))});await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();await open(page);await page.evaluate(()=>finishAvatar());
  expect(await page.evaluate(()=>profileEvents)).toEqual([]);expect(await page.evaluate(()=>calls.filter(c=>c.kind==='profile'))).toEqual([]);await expect(page.locator('[name="displayName"]')).toHaveValue('b');
});
test('closing while login inspection is pending invalidates its response',async({page})=>{
  await fixture(page);await page.evaluate(()=>TravelMateCloud.getSession=()=>new Promise(resolve=>window.finishLogin=()=>resolve({user:window.user})));await page.locator('[data-profile-wizard-open]').click();await page.waitForFunction(()=>window.finishLogin);await page.keyboard.press('Escape');await page.evaluate(()=>finishLogin());await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();expect(await page.evaluate(()=>document.body.style.overflow)).toBe('');
});

test('Image fallback retains a bounded orientation-correct crop',async({page})=>{
  await fixture(page);await open(page);const file=await picture(page,{orientation:6});await page.evaluate(()=>window.createImageBitmap=undefined);await styles(page,file);
  const pixels=await page.locator('[data-profile-crop]').evaluate(canvas=>{const c=canvas.getContext('2d');return [c.getImageData(256,16,1,1).data[0],c.getImageData(256,496,1,1).data[0]]});expect(pixels[0]).toBeGreaterThan(pixels[1]);await page.keyboard.press('Escape');await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});
test('partial preference failure preserves saved avatar and reports uncertainty',async({page})=>{
  await fixture(page);await open(page);await styles(page,await picture(page));await page.locator('[data-profile-next]').click();await page.evaluate(()=>TravelMateCloud.updateProfileForOwner=async()=>({error:new Error('PROFILE_NETWORK_FAILURE')}));await page.locator('[data-profile-save]').click();await expect(page.locator('[data-profile-wizard-status]')).toContainText('התמונה נשמרה');await expect(page.locator('[data-profile-wizard-status]')).toHaveAttribute('role','alert');await expect(page.locator('.profile-wizard-backdrop')).toBeVisible();expect(await page.evaluate(()=>profileEvents)).toEqual(['A']);await page.keyboard.press('Escape');expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});

test('an existing photo generates real previews and saves only the chosen generated avatar',async({page})=>{
  await fixture(page,'dark');const file=await picture(page);await page.route('**/current-photo.jpg',route=>route.fulfill({contentType:'image/jpeg',body:file.buffer}));await page.evaluate(()=>user.user_metadata.avatar_url='http://127.0.0.1:4173/current-photo.jpg');await open(page);await expect(page.locator('[data-profile-next]')).toBeEnabled();await page.locator('[data-profile-next]').click();await page.locator('[value="classic"]').check();await page.locator('[data-profile-next]').click();await page.locator('.profile-extra-details summary').click();await page.locator('[name="displayName"]').fill('שם מעודכן');await page.locator('[name="transport"]').selectOption('transit');await page.locator('[data-profile-save]').click();await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();expect(await page.evaluate(()=>calls)).toEqual([expect.objectContaining({kind:'avatar',owner:'A',style:'classic',dimensions:[512,512]}),expect.objectContaining({kind:'profile',owner:'A',name:'שם מעודכן',preferences:expect.objectContaining({transport:'transit',learningEnabled:false})})]);
});
test('onboarding Step 1 requires a photo and supports camera/gallery at 390 RTL',async({page})=>{
  await page.setViewportSize({width:390,height:844});await fixture(page);await open(page);await expect(page.locator('#profile-wizard-title')).toHaveText('יצירת פרופיל אישי');await expect(page.locator('[data-profile-step="1"] h3')).toHaveText('הוספת תמונה');await expect(page.locator('[data-profile-next]')).toBeDisabled();await expect(page.locator('[data-profile-camera]')).toHaveAttribute('capture','user');await page.locator('[data-profile-gallery]').setInputFiles(await picture(page,{orientation:6}));await expect(page.locator('[data-profile-next]')).toBeEnabled();await bounded(page);await page.keyboard.press('Escape');expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});

test('onboarding Step 2 shows six illustrated styles and requires an explicit keyboard choice',async({page})=>{
  await fixture(page);await open(page);await page.locator('[data-profile-gallery]').setInputFiles(await picture(page));await expect(page.locator('[data-profile-next]')).toBeEnabled();await page.locator('[data-profile-next]').click();await expect(page.locator('[name="avatarStyle"]')).toHaveCount(6);await page.waitForFunction(()=>document.querySelectorAll('.profile-style-card img').length===6);await expect(page.locator('[name="avatarStyle"]:checked')).toHaveCount(0);await expect(page.locator('[data-profile-next]')).toBeDisabled();await expect(page.locator('[data-profile-step="2"] h3')).toHaveText('בחירת אווטר');
  expect(await page.locator('.profile-style-card span').allTextContents()).toEqual(['קלאסי','טוקיו ניאון','רוגע יפני','מסע חופים','מנגה אקשן','סינמטי']);await page.waitForFunction(()=>[...document.querySelectorAll('.profile-style-card img')].every(img=>img.complete&&img.naturalWidth>0));await page.locator('[value="beach-journey"]').focus();await page.keyboard.press('Space');await expect(page.locator('[value="beach-journey"]')).toBeChecked();await expect(page.locator('[data-profile-next]')).toBeEnabled();await bounded(page);await page.screenshot({path:test.info().outputPath('six-avatar-styles.png')});await page.locator('[data-profile-back]').click();await expect(page.locator('[data-profile-next]')).toBeEnabled();await page.locator('[data-profile-next]').click();await expect(page.locator('[value="beach-journey"]')).toBeChecked();
});
test('onboarding Step 3 retains all interest choices and preserves optional profile fields',async({page})=>{
  await fixture(page);await open(page);await styles(page,await picture(page));await page.locator('[data-profile-next]').click();await expect(page.locator('[data-profile-step="3"] h3')).toHaveText('תחומי עניין');await expect(page.locator('[data-profile-save]')).toHaveText('סיום');await expect(page.locator('[data-profile-finish-helper]')).toHaveText('אפשר לשנות אחר כך');
  for(const key of ['food','beaches','museums','families','hiking','photography','technology'])await page.locator('[name="interests"][value="'+key+'"]').check();await expect(page.locator('[name="interests"]:checked')).toHaveCount(8);await page.locator('[data-profile-back]').click();await expect(page.locator('[value="classic"]')).toBeChecked();await page.locator('[data-profile-back]').click();await expect(page.locator('[data-profile-next]')).toBeEnabled();await page.locator('[data-profile-next]').click();await page.locator('[data-profile-next]').click();await expect(page.locator('[name="interests"]:checked')).toHaveCount(8);await bounded(page);await page.locator('[data-profile-save]').click();await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();expect(await page.evaluate(()=>calls.find(c=>c.kind==='profile').preferences.interests)).toEqual(expect.arrayContaining(['beaches','museums','families','hiking','technology']));expect(await page.evaluate(()=>calls.find(c=>c.kind==='profile').preferences)).toMatchObject({pace:'relaxed',learningEnabled:false});
});

// Generation responses below are controlled fixtures, not claims of live AI likeness.
async function beginGeneration(page){await open(page);await page.locator('[data-profile-gallery]').setInputFiles(await picture(page));await expect(page.locator('[data-profile-next]')).toBeEnabled();await page.locator('[data-profile-next]').click()}
async function settled(page){await page.waitForFunction(()=>document.querySelectorAll('.profile-style-card[data-status="ready"],.profile-style-card[data-status="failed"]').length===6)}
test('partial success remains selectable; individual retry preserves other generated images',async({page})=>{
  await fixture(page);await page.evaluate(()=>generationFailures={classic:1,cinematic:1});await beginGeneration(page);await settled(page);expect(await page.evaluate(()=>generationPeak)).toBe(2);expect(await page.evaluate(()=>calls)).toEqual([]);
  await expect(page.locator('[data-style="classic"] [data-style-error]')).toContainText('לא הצלחנו');await page.locator('[value="beach-journey"]').check();const successful=await page.locator('[data-style="beach-journey"] img').getAttribute('src');await page.locator('[data-profile-retry="classic"]').click();await page.waitForFunction(()=>document.querySelector('[data-style="classic"]').dataset.status==='ready');
  expect(await page.evaluate(()=>generationCalls.length)).toBe(7);expect(await page.locator('[data-style="beach-journey"] img').getAttribute('src')).toBe(successful);await expect(page.locator('[value="beach-journey"]')).toBeChecked();await page.locator('[data-profile-next]').click();await expect(page.locator('[data-profile-selected-preview]')).toHaveAttribute('src',successful);await page.keyboard.press('Escape');expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});
test('all failed blocks continuation and retry-all produces real selectable results',async({page})=>{
  await fixture(page);await page.evaluate(()=>generationFailures={'classic':1,'tokyo-neon':1,'japanese-calm':1,'beach-journey':1,'manga-action':1,'cinematic':1});await beginGeneration(page);await settled(page);await expect(page.locator('[data-profile-next]')).toBeDisabled();await expect(page.locator('[data-profile-generation-summary]')).toContainText('נכשלה');await expect(page.locator('[data-profile-retry-all]')).toBeVisible();expect(await page.evaluate(()=>activeUrls.size)).toBe(0);await page.locator('[data-profile-retry-all]').click();await settled(page);await expect(page.locator('.profile-style-card img')).toHaveCount(6);expect(await page.evaluate(()=>generationCalls.length)).toBe(12);await page.keyboard.press('Escape');expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});
test('offline source processing works but generation is never automatically queued',async({page})=>{
  await fixture(page);await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,value:false});dispatchEvent(new Event('offline'))});await beginGeneration(page);await settled(page);await expect(page.locator('[data-profile-generation-summary]')).toContainText('חיבור');await expect(page.locator('[data-profile-next]')).toBeDisabled();expect(await page.evaluate(()=>generationCalls.length)).toBe(0);
  await page.evaluate(()=>{Object.defineProperty(navigator,'onLine',{configurable:true,value:true});dispatchEvent(new Event('online'))});expect(await page.evaluate(()=>generationCalls.length)).toBe(0);await page.locator('[data-profile-retry-all]').click();await settled(page);expect(await page.evaluate(()=>generationCalls.length)).toBe(6);
});
test('generation has two independent requests at most and close aborts stale results',async({page})=>{
  await fixture(page);await page.evaluate(()=>generationWait=true);await beginGeneration(page);await page.waitForFunction(()=>generationCalls.length===2);await expect(page.locator('[data-profile-step="2"]')).toBeVisible();await expect(page.locator('[data-profile-wizard-close]')).toBeEnabled();await expect(page.locator('[data-profile-next]')).toBeDisabled();await page.evaluate(()=>document.querySelector('[data-profile-next]').click());expect(await page.evaluate(()=>generationCalls.length)).toBe(2);await page.locator('[data-profile-wizard-close]').click();await page.evaluate(()=>finishGeneration.forEach(fn=>fn()));await page.waitForFunction(()=>generationInFlight===0);expect(await page.evaluate(()=>activeUrls.size)).toBe(0);expect(await page.evaluate(()=>generationCalls.length)).toBe(2);await open(page);await expect(page.locator('[name="avatarStyle"]')).toHaveCount(0);
});
test('photo replacement rejects outstanding generations from the previous photo',async({page})=>{
  await fixture(page);await page.evaluate(()=>generationWait=true);await beginGeneration(page);await page.waitForFunction(()=>generationCalls.length===2);await page.locator('[data-profile-back]').click();await page.locator('[data-profile-gallery]').setInputFiles(await picture(page,{orientation:6}));await expect(page.locator('[data-profile-next]')).toBeEnabled();await page.evaluate(()=>{generationWait=false;finishGeneration.forEach(fn=>fn())});await page.waitForFunction(()=>generationInFlight===0);expect(await page.evaluate(()=>activeUrls.size)).toBe(0);await page.locator('[data-profile-next]').click();await settled(page);expect(await page.evaluate(()=>generationCalls.length)).toBe(8);await expect(page.locator('[name="avatarStyle"]:checked')).toHaveCount(0);await page.keyboard.press('Escape');expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});
test('account change cancels in-flight generation without painting successor account',async({page})=>{
  await fixture(page);await page.evaluate(()=>generationWait=true);await beginGeneration(page);await page.waitForFunction(()=>generationCalls.length===2);await page.evaluate(()=>{user={id:'B',user_metadata:{}};dispatchEvent(new CustomEvent('travelmate:home-auth',{detail:{authenticated:true}}))});await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();await page.evaluate(()=>finishGeneration.forEach(fn=>fn()));await page.waitForFunction(()=>generationInFlight===0);expect(await page.evaluate(()=>activeUrls.size)).toBe(0);expect(await page.evaluate(()=>calls)).toEqual([]);await open(page);await expect(page.locator('[data-profile-next]')).toBeDisabled();
});
test('Back preserves generations; changing crop invalidates and revokes them',async({page})=>{
  await fixture(page);await open(page);await styles(page,await picture(page));await settled(page);const original=await page.locator('[data-style="classic"] img').getAttribute('src');await page.locator('[data-profile-back]').click();await page.locator('[data-profile-next]').click();await expect(page.locator('[value="classic"]')).toBeChecked();expect(await page.locator('[data-style="classic"] img').getAttribute('src')).toBe(original);expect(await page.evaluate(()=>generationCalls.length)).toBe(6);await page.locator('[data-profile-back]').click();await page.locator('[data-profile-zoom]').fill('1.3');expect(await page.evaluate(()=>activeUrls.size)).toBe(0);await page.locator('[data-profile-next]').click();await settled(page);expect(await page.evaluate(()=>generationCalls.length)).toBe(12);await expect(page.locator('[name="avatarStyle"]:checked')).toHaveCount(0);
});
test('Finish uploads byte-for-byte only the selected generated preview, not the source',async({page})=>{
  await fixture(page);await open(page);await styles(page,await picture(page));await page.locator('[value="cinematic"]').check();const hash=await page.locator('[data-style="cinematic"] img').evaluate(async image=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await (await fetch(image.src)).arrayBuffer()))).join(','));
  await page.evaluate(()=>{const upload=TravelMateCloud.uploadAvatar;TravelMateCloud.uploadAvatar=async(file,options)=>{window.savedHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).join(',');return upload(file,options)}});expect(await page.evaluate(()=>calls.length)).toBe(0);await page.locator('[data-profile-next]').click();await expect(page.locator('.profile-final-avatar')).toBeVisible();await page.locator('[data-profile-save]').click();await expect(page.locator('.profile-wizard-backdrop')).toBeHidden();expect(await page.evaluate(()=>savedHash)).toBe(hash);expect(await page.evaluate(()=>calls.filter(c=>c.kind==='avatar').length)).toBe(1);expect(await page.evaluate(()=>calls[0].style)).toBe('cinematic');expect(await page.evaluate(()=>activeUrls.size)).toBe(0);
});
