'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
function pngSize(path){const b=fs.readFileSync(path);assert.equal(b.toString('hex',0,8),'89504e470d0a1a0a',path+' png signature');return [b.readUInt32BE(16),b.readUInt32BE(20)];}
test('TravelMate icon manifest exposes regular and maskable install assets',()=>{const m=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));const keys=new Set(m.icons.map(i=>i.src+'|'+i.sizes+'|'+i.purpose));for(const k of ['./assets/icons/travelmate-192.png|192x192|any','./assets/icons/travelmate-512.png|512x512|any','./assets/icons/travelmate-maskable-192.png|192x192|maskable','./assets/icons/travelmate-maskable-512.png|512x512|maskable'])assert.ok(keys.has(k),k);});
test('PWA icon raster sizes and home-screen links are complete',()=>{for(const n of [48,72,180,192,512])assert.deepEqual(pngSize('assets/icons/travelmate-'+n+'.png'),[n,n]);for(const n of [192,512])assert.deepEqual(pngSize('assets/icons/travelmate-maskable-'+n+'.png'),[n,n]);for(const file of ['index.html','trip/custom/index.html','trip/italy-2028/index.html','trip/japan-2027/index.html']){const s=fs.readFileSync(file,'utf8');assert.match(s,/travelmate-48\.png/);assert.match(s,/travelmate-180\.png/);}});
test('Android launcher density and adaptive foreground assets have expected geometry',()=>{const legacy={mdpi:48,hdpi:72,xhdpi:96,xxhdpi:144,xxxhdpi:192};const fg={mdpi:108,hdpi:162,xhdpi:216,xxhdpi:324,xxxhdpi:432};for(const [d,n] of Object.entries(legacy)){for(const name of ['ic_launcher.png','ic_launcher_round.png'])assert.deepEqual(pngSize('android/app/src/main/res/mipmap-'+d+'/'+name),[n,n]);}for(const [d,n] of Object.entries(fg))assert.deepEqual(pngSize('android/app/src/main/res/mipmap-'+d+'/ic_launcher_foreground.png'),[n,n]);const bg=fs.readFileSync('android/app/src/main/res/values/ic_launcher_background.xml','utf8');assert.match(bg,/#173E47/);assert.doesNotMatch(bg,/#F5FAF8/);});
test('canonical icon keeps pin airplane AI sparkle and unread badge remains dynamic',()=>{const s=fs.readFileSync('assets/app-icon.svg','utf8');assert.match(s,/M256 62c-91\.68/);assert.match(s,/M179 248l51 13/);assert.match(s,/M357 306l7 20/);assert.match(s,/>AI<\/text>/);assert.doesNotMatch(s,/unread|notification-badge/i);});
test('service worker caches all install icon assets',()=>{const sw=fs.readFileSync('sw.js','utf8');for(const n of ['48','72','180','192','512','maskable-192','maskable-512'])assert.match(sw,new RegExp('travelmate-'+n+'\\.png'));});
