'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const source=fs.readFileSync('supabase/functions/avatar-generator/index.ts','utf8');
const sql=fs.readFileSync('supabase/migrations/20261004220000_avatar_generation_usage.sql','utf8');
const imageData=Buffer.from([255,216,255,192,0,11,8,2,0,2,0,1,1,0,0,255,217]).toString('base64');
const styles=['classic','tokyo-neon','japanese-calm','beach-journey','manga-action','cinematic'];
function boot(options={}){
  let handler;const calls=[];
  const env={SUPABASE_URL:'https://fixture.invalid',SUPABASE_ANON_KEY:'fixture-public',SUPABASE_SERVICE_ROLE_KEY:'fixture-server',GEMINI_API_KEY:'fixture-provider'};
  const fetch=async(url,request)=>{const body=request.body?JSON.parse(request.body):null;calls.push({url,request,body});
    if(url.endsWith('/auth/v1/user'))return Response.json(options.user||{id:'owner-A'},{status:options.authStatus||200});
    if(url.endsWith('claim_avatar_generation'))return Response.json({allowed:options.allowed!==false,claim_id:'claim-fixture'},{status:options.guardStatus||200});
    if(url.endsWith('release_avatar_generation'))return Response.json(null);
    if(options.transport)throw new Error('sensitive-provider-transport');
    if(options.providerStatus)return Response.json({error:'sensitive-image-provider-details'},{status:options.providerStatus});
    return Response.json(options.output||{status:'completed',steps:[{type:'model_output',content:[{type:'image',mime_type:'image/jpeg',data:imageData}]}]});
  };
  vm.runInNewContext(stripTypeScriptTypes(source),{Deno:{env:{get:key=>env[key]},serve:fn=>handler=fn},fetch,Response,Request,TextDecoder,Uint8Array,DataView,atob,btoa,AbortController,AbortSignal,setTimeout,clearTimeout,console:{log:()=>{throw Error('logging prohibited')},error:()=>{throw Error('logging prohibited')}}});
  return{calls,run:(body={},headers={},method='POST')=>handler(new Request('https://edge.invalid',{method,headers:{origin:'https://lioracl.github.io',authorization:'Bearer fixture-session','content-type':'application/json',...headers},...(method==='POST'?{body:JSON.stringify({style:'classic',mimeType:'image/jpeg',imageData,...body})}:{})}))};
}
for(const style of styles)test('Edge generates only allowlisted style '+style,async()=>{const h=boot(),response=await h.run({style});assert.equal(response.status,200);assert.deepEqual(await response.json(),{mimeType:'image/jpeg',imageData});const provider=h.calls.find(c=>c.url.includes('googleapis'));assert.equal(provider.body.model,'gemini-3.1-flash-image');assert.equal(provider.body.store,false);assert.equal(provider.body.response_format.image_size,'0.5K');assert.equal(provider.body.input[1].data,imageData);assert.match(provider.body.input[0].text,/SAME PERSON/);assert.match(provider.body.input[0].text,/never invent hair/);assert.equal(response.headers.get('cache-control'),'no-store');assert.equal(h.calls.at(-1).body.p_owner,'owner-A');});
for(const style of ['unknown','__proto__','constructor'])test('Edge rejects unknown style '+style+' before provider call',async()=>{const h=boot();assert.equal((await h.run({style})).status,400);assert.equal(h.calls.length,0)});
test('Edge origin, method, missing bearer and content type fail closed',async()=>{const h=boot();assert.equal((await h.run({}, {origin:'https://evil.invalid'})).status,403);assert.equal((await h.run({}, {},'GET')).status,405);assert.equal((await h.run({}, {authorization:''})).status,401);assert.equal((await h.run({}, {'content-type':'text/plain'})).status,415);assert.equal(h.calls.length,0);assert.equal((await h.run({}, {},'OPTIONS')).status,204)});
test('Edge rejects malformed, spoofed and oversized images',async()=>{for(const body of [{mimeType:'image/svg+xml'},{imageData:'not-base64'},{mimeType:'image/png'},{imageData:Buffer.alloc(2*1024*1024+1).toString('base64')}]){const h=boot();assert.ok([400,413].includes((await h.run(body)).status));assert.equal(h.calls.length,0)}});
test('Edge validates provider Auth before usage/provider, including anonymous accounts',async()=>{for(const options of [{authStatus:401},{user:{id:'owner',is_anonymous:true}}]){const h=boot(options);assert.equal((await h.run()).status,401);assert.equal(h.calls.length,1)}});
test('usage guard blocks generation and fails closed when unavailable',async()=>{for(const options of [{allowed:false},{guardStatus:500}]){const h=boot(options);assert.equal((await h.run()).status,options.allowed===false?429:503);assert.equal(h.calls.length,2)}});
test('provider failures and transport exceptions are sanitized; claim always released',async()=>{for(const options of [{providerStatus:400},{providerStatus:429},{transport:true}]){const h=boot(options),r=await h.run();assert.equal(r.status,options.providerStatus===429?429:502);assert.doesNotMatch(await r.text(),/sensitive|fixture-provider|fixture-session|imageData/);assert.match(h.calls.at(-1).url,/release_avatar_generation$/)}});
test('missing, multiple, unsafe output and incomplete interaction fail closed',async()=>{for(const output of [{status:'completed',steps:[]},{status:'failed',steps:[]},{status:'completed',steps:[{type:'model_output',content:[{type:'image',mime_type:'image/svg+xml',data:imageData}]}]},{status:'completed',steps:[{type:'model_output',content:[{type:'image',mime_type:'image/jpeg',data:imageData},{type:'image',mime_type:'image/jpeg',data:imageData}]}]}]){const h=boot({output});assert.equal((await h.run()).status,502);assert.match(h.calls.at(-1).url,/release_avatar_generation$/)}});
test('usage migration isolates roles and serializes cost checks with fenced lease release',()=>{assert.match(sql,/enable row level security/);assert.match(sql,/from public, anon, authenticated/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/>=18/);assert.match(sql,/>=2/);assert.match(sql,/interval '30 seconds'/);assert.match(sql,/claim_id=p_claim/);assert.match(sql,/to service_role/);assert.doesNotMatch(sql,/grant.*to authenticated|imageData|access_token/i)});
test('client uses generated blob only and no static/source save fallback',()=>{const wizard=fs.readFileSync('assets/profile-wizard.js','utf8');assert.ok(wizard.includes("isPlaceholder:false,status:'ready'"));assert.ok(wizard.includes('fileFromBlob(chosen.blob,chosen.id)'));assert.ok(!wizard.includes('chosen.blob||onboarding.photo'));assert.ok(!wizard.includes('profile-avatar-previews'));assert.ok(wizard.includes('generationActive<2'));assert.ok(wizard.includes('controller.abort()'));assert.ok(wizard.includes("item.status==='failed'&&(!id||item.id===id)"))});
test('image function has no secret or image logging and cannot accept arbitrary prompts/URLs',()=>{for(const forbidden of ['console.','req.json(','input.prompt','input.url','storage.from'])assert.ok(!source.includes(forbidden));const client=fs.readFileSync('assets/profile-wizard.js','utf8')+fs.readFileSync('assets/cloud-sync.js','utf8');assert.doesNotMatch(client,/GEMINI_API_KEY|SUPABASE_SERVICE_ROLE_KEY/);assert.ok(source.includes('boundedJson(req'))});

function cloudFixture({changedDuringAuth=false,changedAfterFetch=false,status=200,online=true}={}){
  let owner='A';const calls=[];
  const client={auth:{getSession:async()=>({data:{session:{user:{id:owner},access_token:'fixture-token-'+owner}}}),getUser:async()=>({data:{user:{id:changedDuringAuth?'B':owner}}})}};
  const window={__travelMateSupabaseClient:client,TRAVELMATE_SUPABASE:{url:'https://fixture.invalid',publishableKey:'fixture-public'},addEventListener(){},dispatchEvent(){}};
  const fetch=async(url,request)=>{calls.push({url,request,body:JSON.parse(request.body)});if(changedAfterFetch)owner='B';return Response.json(status===200?{mimeType:'image/jpeg',imageData}:{error:'sensitive-provider-error'},{status})};
  vm.runInNewContext(fs.readFileSync('assets/cloud-sync.js','utf8'),{window,fetch,navigator:{onLine:online},localStorage:{getItem(){return null},setItem(){}},document:{},setTimeout,clearTimeout,CustomEvent:function(){},console,Date,Math,Error,Blob,Uint8Array,TextDecoder,btoa,atob,AbortController,DOMException});
  return{cloud:window.TravelMateCloud,calls};
}
test('real client boundary sends normalized photo with captured owner bearer and returns image Blob',async()=>{const h=cloudFixture(),blob=new Blob([Buffer.from(imageData,'base64')],{type:'image/jpeg'});const result=await h.cloud.generateAvatarForOwner('A','classic',blob,new AbortController().signal);assert.equal(result.type,'image/jpeg');assert.equal(result.size,blob.size);assert.equal(h.calls.length,1);assert.equal(h.calls[0].request.headers.Authorization,'Bearer fixture-token-A');assert.equal(h.calls[0].request.cache,'no-store');assert.deepEqual(h.calls[0].body,{style:'classic',mimeType:'image/jpeg',imageData});});
test('client blocks mismatched session/fresh identity before sending personal photo',async()=>{for(const options of [{changedDuringAuth:true},{}]){const h=cloudFixture(options);await assert.rejects(h.cloud.generateAvatarForOwner(options.changedDuringAuth?'A':'B','classic',new Blob(['photo'],{type:'image/jpeg'})),/AUTH_CONTEXT_CHANGED/);assert.equal(h.calls.length,0)}});
test('client rejects results after account switch and does not return a successor blob',async()=>{const h=cloudFixture({changedAfterFetch:true});await assert.rejects(h.cloud.generateAvatarForOwner('A','classic',new Blob(['photo'],{type:'image/jpeg'})),/AUTH_CONTEXT_CHANGED/);assert.equal(h.calls.length,1)});
test('client offline, invalid styles and bad MIME never issue a request',async()=>{const h=cloudFixture({online:false});await assert.rejects(h.cloud.generateAvatarForOwner('A','classic',new Blob(['photo'],{type:'image/jpeg'})),/OFFLINE/);assert.equal(h.calls.length,0);const ready=cloudFixture();await assert.rejects(ready.cloud.generateAvatarForOwner('A','unknown',new Blob(['photo'],{type:'image/jpeg'})),/UNKNOWN_STYLE/);await assert.rejects(ready.cloud.generateAvatarForOwner('A','classic',new Blob(['photo'],{type:'image/svg+xml'})),/INVALID_IMAGE/);assert.equal(ready.calls.length,0)});
test('client provider errors expose only safe status/classification',async()=>{for(const status of [401,429,500,503]){const h=cloudFixture({status});await assert.rejects(h.cloud.generateAvatarForOwner('A','classic',new Blob(['photo'],{type:'image/jpeg'})),error=>{assert.equal(error.status,status);assert.doesNotMatch(error.message,/sensitive/);return true})}});
