'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('assets/learned-preferences.js','utf8');
function api(){const window={dispatchEvent(){}};const sandbox={window,Date,Object,Number,String,Array,Math,URL,CustomEvent:function(t){this.type=t}};vm.runInNewContext(source,sandbox);return window.TravelMateLearnedPreferences}
test('review state transitions are constrained',()=>{const a=api(),c=a.normalizeCandidate({id:'p1',preferenceKey:'pace',value:'balanced',confidence:.5});assert.equal(a.transition(c,'confirmed').reviewState,'confirmed');assert.equal(a.transition(c,'rejected').reviewState,'rejected');assert.equal(a.transition(a.transition(c,'rejected'),'confirmed'),null)});
test('only confirmed choices can personalize',()=>{const a=api(),c=a.normalizeCandidate({id:'p2',preferenceKey:'tripStyle',value:'culture',confidence:.8});assert.equal(a.exportForMate(c,true),null);const yes=a.transition(c,'confirmed');assert.ok(a.exportForMate(yes,true));assert.equal(a.exportForMate(yes,false),null)});
test('evidence requires an allowed structured kind',()=>{const a=api();assert.ok(a.createEvidence({eventKind:'completed_place',sourceTripId:'t1',eventRef:'p1'}));assert.equal(a.createEvidence({eventKind:'unknown_source'}),null)});
test('cross-trip evidence requires matching ownership',()=>{const a=api(),e={sourceOwnerId:'u1',sourceTripId:'t1',eventKind:'completed_place',eventRef:'p1'};assert.ok(a.createOwnedEvidence(e,'u1'));assert.equal(a.createOwnedEvidence(e,'u2'),null);assert.equal(a.createOwnedEvidence({sourceTripId:'t1',eventKind:'completed_place'},'u1'),null)});
test('evidence deduplicates and can be removed',()=>{const a=api(),c=a.normalizeCandidate({id:'p3',preferenceKey:'pace',value:'active',confidence:.4}),e={eventKind:'completed_activity',sourceTripId:'t1',eventRef:'a1',weight:1};const one=a.addEvidence(c,e,.2),two=a.addEvidence(one,e,.2);assert.equal(one.confidence,.6);assert.equal(two.evidence.length,1);const removed=a.removeEvidence(two,x=>x.sourceTripId==='t1');assert.equal(removed.evidence.length,0);assert.ok(removed.confidence<two.confidence)});
