'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('assets/document-vault.js','utf8');
// Minimal structural DOM fixture for the markup/relocation contract; no cloud calls.
class Element {
 constructor(tag='div',attrs={}){this.tag=tag;this.attrs=attrs;this.children=[];this.dataset={};this.hidden='hidden' in attrs;this.style={};this.classList={toggle(){}};this.value='';}
 set className(v){this.attrs.class=v;} get className(){return this.attrs.class||'';}
 setAttribute(k,v){this.attrs[k]=v;} appendChild(e){if(e.parentNode)e.parentNode.children.splice(e.parentNode.children.indexOf(e),1);this.children.push(e);e.parentNode=this;return e;}
 insertAdjacentElement(where,e){const p=this.parentNode,index=p.children.indexOf(this);if(e.parentNode)e.parentNode.children.splice(e.parentNode.children.indexOf(e),1);p.children.splice(index+(where==='afterend'?1:0),0,e);e.parentNode=p;}
 set innerHTML(html){this.children=[];const stack=[this];for(const m of html.matchAll(/<\/?([\w-]+)([^>]*)>/g)){if(m[0][1]==='/'){if(stack.length>1)stack.pop();continue;}const attrs={};for(const a of m[2].matchAll(/([\w-]+)(?:="([^"]*)")?/g))attrs[a[1]]=a[2]||'';const e=new Element(m[1],attrs);stack[stack.length-1].appendChild(e);if(!['input','img','br','hr','meta','link'].includes(m[1]))stack.push(e);}}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 querySelectorAll(selector){const result=[];const matches=e=>selector[0]==='.'?e.className.split(' ').includes(selector.slice(1)):selector[0]==='['?selector.slice(1,-1) in e.attrs:selector[0]==='#'?e.attrs.id===selector.slice(1):e.tag===selector;const walk=e=>{for(const c of e.children){if(matches(c))result.push(c);walk(c);}};walk(this);return result;}
 contains(e){return this===e||this.children.some(c=>c.contains(e));}
}
function fixture(){const section=new Element('section',{id:'documents'});section.innerHTML='<div class="section-head"></div><nav data-documents-category-nav></nav><div class="doc-list" data-document-category-list><article class="doc-row" data-document-group="flights"><button>Upload</button></article></div><article data-ai-notes-archive></article>';const list=section.querySelector('[data-document-category-list]'),row=list.children[0],archive=section.querySelector('[data-ai-notes-archive]');const context={section,document:{createElement:tag=>new Element(tag)}};vm.createContext(context);const markup=source.slice(source.indexOf('function createVaultMarkup()'),source.indexOf('async function init()'));const setup=source.slice(source.indexOf("var vault = document.createElement('div');"),source.indexOf("var status = vault.querySelector"));vm.runInContext(markup+'\n'+setup,context);return {...context,list,row,archive};}
test('Documents creates one library and all summary nodes outside intro/access',()=>{const {section}=fixture();const lib=section.querySelector('.vault-library');assert.ok(lib);for(const attr of ['data-vault-summary','data-vault-count','data-vault-size','data-vault-storage']){assert.equal(section.querySelectorAll('['+attr+']').length,1);assert.ok(lib.contains(section.querySelector('['+attr+']')));}assert.equal(section.querySelector('.vault-intro').contains(lib),false);assert.equal(section.querySelector('.vault-access').contains(lib),false);});
test('library relocation preserves existing category row identity and separate Mate archive',()=>{const {section,list,row,archive}=fixture(),lib=section.querySelector('.vault-library');assert.ok(lib.contains(list));assert.equal(list.children[0],row);assert.ok(lib.contains(section.querySelector('[data-documents-category-nav]')));assert.equal(lib.contains(archive),false);assert.equal(archive.parentNode,section);const ai=fs.readFileSync('assets/ai-assistant.js','utf8');assert.match(ai,/var host = documents\.querySelector\('\.vault-library'\)/);});
test('real session visibility statements work signed out and signed in with reconstructed summary',()=>{const {section}=fixture();const ctx={currentUser:null,documentSessionEpoch:0,authPanel:section.querySelector('[data-vault-auth]'),sessionPanel:section.querySelector('[data-vault-session]'),unlockPanel:section.querySelector('[data-vault-unlock]'),uploadSection:section.querySelector('[data-vault-upload-section]'),form:section.querySelector('[data-vault-form]'),summary:section.querySelector('[data-vault-summary]'),vaultPickButtons:[]};vm.createContext(ctx);const statements=source.slice(source.indexOf('var sessionEpoch = ++documentSessionEpoch;'),source.indexOf("vault.querySelector('[data-vault-email]')"));for(const session of [null,{user:{id:'fixture-user'}}]){ctx.session=session;assert.doesNotThrow(()=>vm.runInContext(statements,ctx));assert.equal(ctx.summary.hidden,!session);assert.equal(ctx.uploadSection.hidden,!session);assert.equal(ctx.authPanel.hidden,Boolean(session));}});
test('six surface choices have paired light/dark families and keep safe preference defaults',()=>{const theme=fs.readFileSync('assets/theme.js','utf8'),css=fs.readFileSync('assets/readable-glass.css','utf8'),settings=fs.readFileSync('assets/security-center.js','utf8');for(const key of ['classic','ice-aqua','pearl-blue','warm-sand','soft-lilac','nordic-slate']){assert.ok(theme.includes(key));assert.ok(css.includes('html[data-surface-theme="'+key+'"]'));assert.ok(css.includes('html[data-theme="dark"][data-surface-theme="'+key+'"]'));}assert.ok(settings.includes('מראה האפליקציה'));assert.ok(settings.includes('בחר את סגנון הכרטיסים והפקדים. צבע ההדגשה נבחר בנפרד.'));});

test('all six Surface Themes normalize and reload independently of mode and accent',()=>{
 const source=fs.readFileSync('assets/theme.js','utf8');
 const boot=values=>{const root={dataset:{},style:{setProperty(){}}},window={dispatchEvent(){}};vm.runInNewContext(source,{document:{documentElement:root,readyState:'complete',querySelectorAll:()=>[],addEventListener(){}},window,localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},CustomEvent:function(){}});return {api:window.TravelMateTheme,root};};
 for(const key of ['classic','ice-aqua','pearl-blue','warm-sand','soft-lilac','nordic-slate']){const values=new Map([['travelmate-theme','dark'],['travelmate-accent','plum']]);const e=boot(values);assert.equal(e.api.normalizeSurfaceTheme(key),key);e.api.setSurfaceTheme(key);const restored=boot(values);assert.equal(restored.root.dataset.surfaceTheme,key);assert.equal(restored.root.dataset.theme,'dark');assert.equal(restored.root.dataset.accent,'plum');}
 assert.equal(boot(new Map()).root.dataset.surfaceTheme,'ice-aqua');assert.equal(boot(new Map([['travelmate-surface-theme','invalid']])).root.dataset.surfaceTheme,'classic');
});

test('independent Mate archive consumes a valid paired theme surface, not a nested gradient',()=>{const c=fs.readFileSync('assets/document-vault.css','utf8'),rule=c.match(/#documents \.ai-notes-archive\{([^}]+)\}/)[1];assert.match(rule,/background:var\(--tm-surface-glass\)/);assert.match(rule,/color:var\(--tm-card-text\)/);assert.doesNotMatch(rule,/linear-gradient/);});
