'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const smart=require('../assets/smart-trip-mode.js');
const read=name=>fs.readFileSync('assets/'+name,'utf8');
function boot(overrides={}){const window={dispatchEvent(){},...overrides};const scope={window,CustomEvent:function(){},URL,location:{href:"https://example.invalid/"},Date,Object,Array,String,Promise,console};vm.runInNewContext(read('user-profile.js'),scope);vm.runInNewContext(read('personalized-suggestions.js'),scope);return{window,profile:window.TravelMateUserProfile,fit:window.TravelMatePersonalizedSuggestions}}
const json=value=>JSON.parse(JSON.stringify(value));
test('existing users retain exact neutral legacy preference shape and consent',()=>{const {profile,fit}=boot();const p=profile.fromUser({id:'A',user_metadata:{}}).preferences;assert.equal(Object.hasOwn(p,'profile2'),false);assert.equal(p.pace,'');assert.equal(p.learningEnabled,false);assert.equal(fit.build([],[],p).isEmpty,true)});
test('Profile 2.0 normalization is bounded, deduplicated, neutral and extensible',()=>{const {profile}=boot();const p=profile.normalizePreferences({pace:'intensive',interests:['nature'],profile2:{walking:'short',transport:['transit','transit','invalid'],activeHours:['evening'],exclusions:['nightlife','future_category','<script>']}});assert.equal(p.pace,'intensive');assert.deepEqual(json(p.profile2.transport),['transit']);assert.deepEqual(json(p.profile2.exclusions),['nightlife','future_category']);assert.equal(p.profile2.spending,'');assert.equal(profile.preferenceSummary(p).isEmpty,false);assert.equal(Object.keys(profile.travelerGroups).length,7)});
test('cached Auth metadata reloads account-owned explicit preferences without another store',()=>{const {profile}=boot();const a={id:'A',user_metadata:{avatar_url:'https://example.invalid/a.jpg',travelmate_preferences:{interests:['nature'],learningEnabled:true,profile2:{walking:'short'}}}};const cached=json(a);assert.equal(profile.fromUser(cached).preferences.profile2.walking,'short');assert.deepEqual(json(profile.fromUser(cached).preferences.interests),['nature']);assert.equal(profile.fromUser({id:'B',user_metadata:{}}).preferences.profile2,undefined);assert.equal(cached.user_metadata.avatar_url,a.user_metadata.avatar_url)});
test('explicit exclusions override both declared and approved learned suggestions',()=>{const {fit}=boot();const context=fit.build(['food'],['nightlife','museums'],{profile2:{exclusions:['nightlife','museums']}});assert.deepEqual(json(context.learned),[]);assert.equal(fit.reasonForCategory('bars',context),null);assert.equal(fit.reasonForCategory('museums',context),null);assert.ok(!fit.categoriesFor(context,['bars','museums','parks'],20).includes('bars'));assert.ok(context.categoryKeys.includes('restaurants'))});
test('explicit style changes advisory ranking without mutating place data',()=>{const {fit}=boot();const places=[{id:1,category:'viewpoint',walkingMinutes:45},{id:2,category:'cafe',walkingMinutes:5},{id:3,category:'restaurant',priceLevel:4}];const before=JSON.stringify(places),context=fit.build([],[],{pace:'relaxed',profile2:{walking:'short',spending:'economical',food:['cafes'],transport:['transit']}});assert.equal(fit.rankPlaces(places,context)[0].id,2);assert.equal(JSON.stringify(places),before);assert.match(fit.profileReason(context),/הליכה קצרה/)});
test('strong known walking/cost exclusions filter recommendations but preserve manual searches',()=>{const {fit}=boot(),context=fit.build([],[],{profile2:{exclusions:['long_walks','expensive_places']}});const places=[{id:1,category:'cafe',priceLevel:1},{id:2,category:'viewpoint',walkingMinutes:60},{id:3,category:'restaurant',priceLevel:4}];assert.deepEqual(fit.rankPlaces(places,context).map(x=>x.id),[1]);assert.equal(fit.rankPlaces(places,context,true).length,3);assert.equal(fit.reasonForPlace(places[2],'restaurants',context),null)});
test('active hours and early-morning exclusion have deterministic local periods',()=>{const {fit}=boot();const context=fit.build([],[],{profile2:{activeHours:['evening'],exclusions:['early_mornings']}});assert.equal(fit.activeAt(context,new Date(2026,9,6,18)),true);assert.equal(fit.activeAt(context,new Date(2026,9,6,7)),false);assert.equal(fit.activeAt(context,new Date(2026,9,6,13)),false)});
function suggestion(fit,preferences,minutes=60,hour=18,weather={ready:false}){const trip={id:'T',activities:[{id:'fixed'}]},before=JSON.stringify(trip),model={phase:'ACTIVE',today:'2026-10-06',currentOrNext:null};const result=smart.buildSuggestion(trip,new Date(2026,9,6,hour),fit.build([],[],preferences),weather,{personalized:fit,today:{model(){return model}},context:{nextFixedActivity(){return null},availableMinutesUntilNextFixed(){return null},freeTimeWindowsForDate(){return[{durationMinutes:minutes}]},clockTime(){return'18:00'}}});assert.equal(JSON.stringify(trip),before);return result}
test('Smart Trip respects relaxed short windows without rewriting itinerary',()=>{const {fit}=boot();const s=suggestion(fit,{pace:'relaxed'});assert.equal(s.kind,'rest-window');assert.equal(s.action.href,'#plan');assert.match(s.profileReason,/נינוח/)});
test('Smart Trip avoids suggesting activity outside explicit hours and excluded indoor categories',()=>{const {fit}=boot();assert.equal(suggestion(fit,{profile2:{activeHours:['morning']}}).kind,'preferred-hours');const s=suggestion(fit,{profile2:{exclusions:['museums','shopping']}},120,18,{ready:true,weatherCode:61});assert.notEqual(s.action.categoryKey,'museums');assert.notEqual(s.action.categoryKey,'malls')});
test('in-flight learned lookup cannot attach predecessor preferences to the next account',async()=>{let resolve;const a={id:'A',user_metadata:{travelmate_preferences:{learningEnabled:true,profile2:{walking:'short'}}}},b={id:'B',user_metadata:{}};let current=a;const {fit}=boot({TravelMateCloud:{getSession:async()=>({user:current})},TravelMateLearnedProfile:{confirmedForMate:()=>new Promise(done=>resolve=done)}});const pending=fit.current();await new Promise(setImmediate);current=b;resolve([{preferenceKey:'interests',value:'food',reviewState:'confirmed'}]);assert.equal((await pending).isEmpty,true);assert.equal((await fit.current()).isEmpty,true)});
test('offline learned lookup failure retains only current explicit cached preferences',async()=>{const {fit}=boot({TravelMateCloud:{getSession:async()=>({user:{id:'A',user_metadata:{travelmate_preferences:{learningEnabled:true,profile2:{walking:'short'}}}}})},TravelMateLearnedProfile:{confirmedForMate:async()=>{throw Error('offline')}}});const p=await fit.current();assert.equal(p.profile2.walking,'short');assert.deepEqual(json(p.learned),[])});
test('Today Brief consumes existing Smart Trip explanation without AI GPS search or persistence',()=>{const source=read('today-brief.js');assert.match(source,/s.reason/);assert.match(source,/travelmate:smart-trip-updated/);assert.doesNotMatch(source,/fetch\s*\(|geolocation|generateAvatar|executePlacesSearch|saveTrip\s*\(/)});
test('Places profile hydration never initiates search and account changes clear prior context',()=>{const s=read('nearby.js'),start=s.indexOf('async function hydratePersonalization'),end=s.indexOf('function clearPoiMarkers',start),part=s.slice(start,end);assert.doesNotMatch(part,/executePlacesSearch\s*\(|currentPosition\s*\(|searchAt\s*\(/);assert.match(part,/_travelMatePersonalization=null/);assert.match(s,/travelmate:home-auth/)});
test('Profile 2.0 uses existing semantic RTL controls without important or new surface debt',()=>{const css=read('profile-wizard.css').split('Profile 2.0')[1];assert.ok(css);assert.doesNotMatch(css,/!important|backdrop-filter/);assert.match(css,/min-width:0/);assert.match(read('profile-wizard.js'),/data-traveler-reset/);assert.match(read('profile-wizard.js'),/updatePreferencesForOwner/)});


test('disabling learned preferences preserves explicit Profile 2.0 and prompts prioritize exclusions',()=>{assert.match(read('learned-profile.js'),/preferences.profile2=profile.preferences.profile2/);const s=read('trip-intelligence.js');assert.equal((s.match(/סדר עדיפויות:/g)||[]).length,2);assert.match(s,/החרגות מפורשות/)});
test('Smart Trip commits asynchronous context only after its session/request fence',()=>{const s=read('smart-trip-mode.js');assert.match(s,/nextContext=await personalization\(\)/);assert.match(s,/if\(run!==generation\|\|!card.isConnected\)return;lastContext=nextContext/)});
test('logout and same-account reauthentication invalidate an outstanding preference snapshot',async()=>{let complete,current={id:'A',user_metadata:{travelmate_preferences:{learningEnabled:true,profile2:{walking:'short'}}}};const events={};const {fit}=boot({addEventListener:(name,fn)=>events[name]=fn,TravelMateCloud:{getSession:async()=>({user:current})},TravelMateLearnedProfile:{confirmedForMate:()=>new Promise(resolve=>complete=resolve)}});const pending=fit.current();await new Promise(setImmediate);events['travelmate:home-auth']();current={id:'A',user_metadata:{}};events['travelmate:home-auth']();complete([]);assert.equal((await pending).isEmpty,true)});


test('existing delete-all-learned action disables consent without dropping Profile 2.0',async()=>{
  const {window}=boot();let user={id:'A',user_metadata:{avatar_url:'https://example.invalid/a.jpg',travelmate_preferences:{pace:'relaxed',interests:['food'],learningEnabled:true,profile2:{walking:'short',exclusions:['nightlife']}}}},writes=[],rpcs=[];
  window.TravelMateCloud={getSession:async()=>({user}),scopedClientForOwner:async owner=>({ownerId:owner,session:{user},client:{rpc:async name=>{rpcs.push(name);return{data:2,error:null}}}}),updatePreferencesForOwner:async(owner,preferences)=>{assert.equal(owner,'A');writes.push(preferences);user={...user,user_metadata:{...user.user_metadata,travelmate_preferences:preferences}};return{data:{user},error:null}}};
  vm.runInNewContext(read('learned-profile.js'),{window,navigator:{onLine:true},CustomEvent:function(){},Date,Object,Array,String,Promise,console});await window.TravelMateLearnedProfile.deleteAllAndDisable();assert.equal(writes[0].learningEnabled,false);assert.equal(writes[0].profile2.walking,'short');assert.deepEqual(json(writes[0].interests),['food']);assert.equal(user.user_metadata.avatar_url,'https://example.invalid/a.jpg');assert.deepEqual(rpcs,['travelmate_delete_all_learned_preferences']);
});
