const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.join(__dirname,'..');
const js=fs.readFileSync(path.join(root,'assets/today-brief.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/today-brief.css'),'utf8');
const html=fs.readFileSync(path.join(root,'trip/custom/index.html'),'utf8');
assert(html.includes('today-brief.css'),'custom trip must load Today Brief styles');
assert(html.includes('today-brief.js'),'custom trip must load Today Brief logic');
['data-readiness-open','Trip Health Check','תוכנית בסיסית','לינה וכתובת','תקציב ומטבע','מסמכים חשובים','העדפות אישיות','זמינות אופליין'].forEach(x=>assert(js.includes(x),'missing '+x));
assert(js.includes('availableMinutesUntilNextFixed'),'Today Brief must reuse free-time context');
assert(js.includes('[data-smart-trip-mode]'),'Today Brief must reuse Smart Trip recommendation');
assert(js.includes('[data-weather-summary]'),'Today Brief must reuse rendered weather without fetching');
assert(!/geolocation|getCurrentPosition|watchPosition/.test(js),'Today Brief must not request GPS');
assert(!/fetch\s*\(|XMLHttpRequest|askAi|generate/i.test(js),'Today Brief must not start network or AI work');
assert(!/MutationObserver/.test(js),'Today Brief must not add a broad DOM observer');
assert(js.includes('TravelMateNavigation.open'),'Brief actions must use canonical trip navigation');
assert(css.includes('@media(max-width:430px)'),'mobile 430 contract required');
assert(css.includes('min-height:44px')||css.includes('height:44px'),'touch targets must be 44px');
assert(js.includes("ev.key==='Escape'"),'dialog must support Escape');
console.log('today-brief-contract: PASS');