'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const contextSource=fs.readFileSync('assets/trip-context.js','utf8');
const analyticsSource=fs.readFileSync('assets/trip-analytics.js','utf8');
function loadAnalytics(){const window={dispatchEvent(){}};const sandbox={window,Date,Object,Number,String,Array,Math,URL,Set,CustomEvent:function(type){this.type=type}};vm.runInNewContext(contextSource,sandbox);vm.runInNewContext(analyticsSource,sandbox);return window.TravelMateTripAnalytics}
function sampleTrip(){return {activities:[
{id:'a1',title:'Museum',date:'2026-10-01',time:'09:00',done:true,lat:50.08,lon:14.42},
{id:'a2',title:'Cafe',date:'2026-10-01',time:'12:00',done:true,lat:50.09,lon:14.43,travelMode:'walk'},
{id:'a3',title:'Not visited',date:'2026-10-01',time:'15:00',done:false,lat:51,lon:15}
],savedPlaces:[{id:'p1',name:'Old Town',date:'2026-10-02',time:'10:00',done:true,lat:50.081,lon:14.421}],expenses:[
{id:'e1',amount:10,currency:'EUR',category:'אוכל/קפה',date:'2026-10-01'},
{id:'e2',amount:40,currency:'ILS',category:'קניות/מזכרות',date:'2026-10-01'},
{id:'e3',amount:5,currency:'EUR',category:'תחבורה',date:'2026-10-02'}
]}}
test('Trip Summary V2 keeps money grouped by currency and category',()=>{const data=loadAnalytics().build(sampleTrip());assert.equal(data.expenses.count,3);assert.equal(data.expenses.totals.EUR,15);assert.equal(data.expenses.totals.ILS,40);assert.equal(data.expenses.categories.find(x=>x.name==='קניות').totals.ILS,40);assert.equal(data.status.expenses,'confirmed')});
test('Trip Summary V2 route includes only completed visits with stored coordinates',()=>{const data=loadAnalytics().build(sampleTrip());assert.equal(data.route.pointCount,3);assert.equal(data.route.points.some(x=>x.title==='Not visited'),false);assert.equal(data.route.pointStatus,'confirmed');assert.equal(data.route.pathStatus,'estimated')});
test('Trip Summary V2 exposes daily confirmed visits, movement and expenses separately',()=>{const data=loadAnalytics().build(sampleTrip());const first=data.summaryDays.find(x=>x.date==='2026-10-01');assert.equal(first.completedVisits,2);assert.equal(first.expenseCount,2);assert.equal(first.expenseTotals.EUR,10);assert.equal(first.expenseTotals.ILS,40);assert.ok(first.movement.distanceKm>0)});
test('Trip Replay never merges unlike currencies into one total',()=>{const analytics=loadAnalytics();const window={addEventListener(){},TravelMateEvents:null,TravelMateTripAnalytics:analytics};const document={readyState:'loading',addEventListener(){},getElementById(){return null}};const sandbox={window,document,navigator:{onLine:true},location:{search:'',pathname:'/trip/custom/'},URLSearchParams,Date,Object,Number,String,Array,Math,Intl,Promise,setTimeout(){}};vm.runInNewContext(fs.readFileSync('assets/trip-replay.js','utf8'),sandbox);const replay=window.TravelMateTripReplay.build(sampleTrip());assert.equal(replay.expenseTotal,0);assert.equal(replay.expenseLabels.length,2);assert.match(replay.expenseLabel,/EUR|€/);assert.match(replay.expenseLabel,/ILS|₪/)});
test('Trip Summary route map is on-demand, factual and does not request location',()=>{const source=fs.readFileSync('assets/trip-replay.js','utf8');const css=fs.readFileSync('assets/trip-replay.css','utf8');assert.match(source,/data-trip-summary-map-toggle/);assert.match(source,/analytics\.route/);assert.match(source,/OpenFreeMap|openfreemap/);assert.doesNotMatch(source,/getCurrentPosition|navigator\.geolocation/);assert.match(source,/travelmate-summary-route/);assert.match(css,/min-height:44px/);assert.doesNotMatch(css,/!important/)});
test('Trip Replay fallback also keeps mixed and unknown currencies separate',()=>{const window={addEventListener(){},TravelMateEvents:null};const document={readyState:'loading',addEventListener(){},getElementById(){return null}};const sandbox={window,document,navigator:{onLine:true},location:{search:'',pathname:'/trip/custom/'},URLSearchParams,Date,Object,Number,String,Array,Math,Intl,Promise,setTimeout(){}};vm.runInNewContext(fs.readFileSync('assets/trip-replay.js','utf8'),sandbox);const replay=window.TravelMateTripReplay.build({expenses:[{amount:4,currency:'EUR'},{amount:7,currency:'ILS'},{amount:3,currency:''}]});assert.equal(replay.expenseTotal,0);assert.equal(replay.expenseLabels.length,3);assert.match(replay.expenseLabel,/מטבע לא ידוע/)});
test('Trip Summary does not label an invalid currency as EUR',()=>{const data=loadAnalytics().build({expenses:[{amount:9,currency:'??',category:'אחר',date:'2026-10-01'}]});assert.equal(data.expenses.totals.UNKNOWN,9);assert.equal(data.expenses.totals.EUR,undefined)});
test('Unscheduled completed saved places stay ideas, not completed visits',()=>{const analytics=loadAnalytics().build({savedPlaces:[{id:'p',name:'Idea',done:true,lat:50,lon:14}]});assert.equal(analytics.completedVisits,0);const window={addEventListener(){},TravelMateEvents:null,TravelMateTripAnalytics:loadAnalytics()};const document={readyState:'loading',addEventListener(){},getElementById(){return null}};const sandbox={window,document,navigator:{onLine:true},location:{search:'',pathname:'/trip/custom/'},URLSearchParams,Date,Object,Number,String,Array,Math,Intl,Promise,setTimeout(){}};vm.runInNewContext(fs.readFileSync('assets/trip-replay.js','utf8'),sandbox);const replay=window.TravelMateTripReplay.build({savedPlaces:[{id:'p',name:'Idea',done:true}]});assert.equal(replay.completed,0);assert.equal(replay.savedOnly,1)});
test('Mate Replay prompt excludes private memory note text and note fallback cannot become a visit title',()=>{const analytics=loadAnalytics();const window={addEventListener(){},TravelMateEvents:null,TravelMateTripAnalytics:analytics};const document={readyState:'loading',addEventListener(){},getElementById(){return null}};const sandbox={window,document,navigator:{onLine:true},location:{search:'',pathname:'/trip/custom/'},URLSearchParams,Date,Object,Number,String,Array,Math,Intl,Promise,setTimeout(){}};vm.runInNewContext(fs.readFileSync('assets/trip-replay.js','utf8'),sandbox);const api=window.TravelMateTripReplay,data=api.build({activities:[{id:'a',date:'2026-10-01',done:true,note:'PRIVATE_VISIT_NOTE'}],memories:[{date:'2026-10-01',note:'PRIVATE_MEMORY_NOTE'}]});assert.doesNotMatch(api.prompt(data),/PRIVATE_MEMORY_NOTE/);assert.doesNotMatch(api.prompt(data),/PRIVATE_VISIT_NOTE/)});
test('Summary map groups line geometry by day and invalidates stale async loads',()=>{const source=fs.readFileSync('assets/trip-replay.js','utf8');assert.match(source,/byDate\[point\.date\]/);assert.match(source,/FeatureCollection/);assert.match(source,/day\.length>1/);assert.match(source,/summaryMapRequestId/);assert.match(source,/requestId!==summaryMapRequestId/);assert.match(source,/summaryMap\.remove\(\)/);assert.match(source,/מפת נקודות הביקור/)});
